### ISSUE TITLE
RPC-CORE: getMetadata(at?: BlockHash): Metadata:: createType(Metadata):: Unable to create Enum via index 6, in Blake2_128, Blake2_256, Blake2_128Concat, Twox128, Twox256, Twox64Concat

### ISSUE THREAD

**Issue by achiko** [PolymathNetwork/polymesh-sdk#201]
**Polymesh-2.0.1 ** 
`./target/debug/polymesh --chain alcyone --rpc-external --ws-external --rpc-cors all`

ws connection is open :  

**Code Sampe**
```
import { stringToU8a } from "@polkadot/util";
import { Polymesh } from "@polymathnetwork/polymesh-sdk";

(async () => {
  const polyClient = await Polymesh.connect({
    nodeUrl: "ws://<my node ip>:9944",
    accountSeed: <my seed>,
  });

})();

```
Error : 

```
 2020-09-11 19:19:25        RPC-CORE: getMetadata(at?: BlockHash): Metadata:: createType(Metadata):: Unable to create Enum via index 6, in Blake2_128, Blake2_256, Blake2_128Concat, Twox128, Twox256, Twox64Concat
 2020-09-11 19:19:26   API/DECORATOR: Error: FATAL: Unable to initialize the API: getMetadata(at?: BlockHash): Metadata:: createType(Metadata):: Unable to create Enum via index 6, in Blake2_128, Blake2_256, Blake2_128Concat, Twox128, Twox256, Twox64Concat
     at ApiPromise.<anonymous> (~app/polymesh-sdk-test/node_modules/@polymathnetwork/polkadot/api/base/Init.js:50:31)
     at Generator.throw (<anonymous>)
     at rejected (~app/polymesh-sdk-test/node_modules/@polymathnetwork/polkadot/api/base/Init.js:9:65)
     at processTicksAndRejections (internal/process/task_queues.js:97:5)
 (node:71833) UnhandledPromiseRejectionWarning: Error: Error while connecting to "ws://95.217.23.177:9944": "FATAL: Unable to initialize the API: getMetadata(at?: BlockHash): Metadata:: createType(Metadata):: Unable to create Enum via index 6, in Blake2_128, Blake2_256, Blake2_128Concat, Twox128, Twox256, Twox64Concat"
     at Function.<anonymous> (~app/polymesh-sdk-test/node_modules/@polymathnetwork/polymesh-sdk/Polymesh.js:44:23)
     at Generator.throw (<anonymous>)
     at rejected (~app/polymesh-sdk-test/node_modules/@polymathnetwork/polymesh-sdk/Polymesh.js:6:65)
     at processTicksAndRejections (internal/process/task_queues.js:97:5)
 (Use `node --trace-warnings ...` to show where the warning was created)
 (node:71833) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
 (node:71833) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

**Comment by monitz87** [comment]
Which version of the SDK are you using?

**Comment by achiko** [comment]
"@polymathnetwork/polymesh-sdk": "^1.0.0-beta.1",

**Comment by VictorVicente** [comment]
Please, try with latest beta version. At the moment: `1.0.0-beta.144`
Polymesh has changed a lot since it started and the SDK too :)
